name: raster2seq
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-12.6.0
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cccl=2.7.0=h280d941_0
  - cuda-cccl=12.8.90=h06a4308_1
  - cuda-cccl_linux-64=12.8.90=h06a4308_1
  - cuda-command-line-tools=12.6.0=0
  - cuda-compiler=12.6.0=0
  - cuda-crt-dev_linux-64=12.8.93=h06a4308_3
  - cuda-crt-tools=12.8.93=h06a4308_3
  - cuda-cudart=12.8.90=hbdd6827_0
  - cuda-cudart-dev=12.8.90=hbdd6827_0
  - cuda-cudart-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart-static=12.8.90=hbdd6827_0
  - cuda-cudart-static_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-cuobjdump=12.8.90=h5b7f43c_1
  - cuda-cupti=12.8.90=hbdd6827_1
  - cuda-cupti-dev=12.8.90=hbdd6827_1
  - cuda-cuxxfilt=12.8.90=h5b7f43c_1
  - cuda-driver-dev=12.8.90=hbdd6827_0
  - cuda-driver-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-gdb=12.8.90=ha410205_1
  - cuda-libraries=12.6.0=0
  - cuda-libraries-dev=12.6.0=0
  - cuda-nsight=12.8.90=h6061065_1
  - cuda-nvcc=12.8.93=h02f8991_2
  - cuda-nvcc-dev_linux-64=12.8.93=he2511ca_3
  - cuda-nvcc-impl=12.8.93=hd1a145a_3
  - cuda-nvcc-tools=12.8.93=hbdd6827_3
  - cuda-nvcc_linux-64=12.8.93=h2f703a9_2
  - cuda-nvdisasm=12.8.90=h5b7f43c_1
  - cuda-nvml-dev=12.8.90=h5b7f43c_1
  - cuda-nvprof=12.8.90=h5b7f43c_1
  - cuda-nvprune=12.8.90=h5b7f43c_1
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-nvrtc-dev=12.8.93=hbdd6827_1
  - cuda-nvtx=12.8.90=hbdd6827_1
  - cuda-nvvm-dev_linux-64=12.8.93=h06a4308_3
  - cuda-nvvm-impl=12.8.93=hbdd6827_3
  - cuda-nvvm-tools=12.8.93=hbdd6827_3
  - cuda-nvvp=12.8.93=h5b7f43c_1
  - cuda-opencl=12.8.90=hb6f8877_1
  - cuda-opencl-dev=12.8.90=hbdd6827_1
  - cuda-profiler-api=12.8.90=h6061065_1
  - cuda-sanitizer-api=12.8.93=h5b7f43c_1
  - cuda-toolkit=12.6.0=0
  - cuda-tools=12.6.0=0
  - cuda-version=12.8=h30beaf8_3
  - cuda-visual-tools=12.6.0=0
  - dbus=1.16.2=h5bd4931_0
  - einops=0.8.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=14.3.0=h4943218_4
  - gcc_linux-64=14.3.0=hda73cce_11
  - gds-tools=1.13.1.3=h6d59cf1_1
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=14.3.0=he634eba_4
  - gxx_linux-64=14.3.0=hca8765c_11
  - icu=73.1=h6a678d5_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.8.4.1=hbdd6827_1
  - libcublas-dev=12.8.4.1=hbdd6827_1
  - libcufft=11.3.3.83=hbdd6827_1
  - libcufft-dev=11.3.3.83=hbdd6827_1
  - libcufile=1.13.1.3=h5cefc81_1
  - libcufile-dev=1.13.1.3=hbdd6827_1
  - libcurand=10.3.9.90=hbdd6827_1
  - libcurand-dev=10.3.9.90=hbdd6827_1
  - libcusolver=11.7.3.90=hbdd6827_1
  - libcusolver-dev=11.7.3.90=hbdd6827_1
  - libcusparse=12.5.8.93=hbdd6827_1
  - libcusparse-dev=12.5.8.93=hbdd6827_1
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=he7458c1_104
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libjpeg-turbo=3.1.2=hfdadbec_0
  - libkrb5=1.21.3=h520c7b4_4
  - libnl=3.11.0=hb25bd0a_0
  - libnpp=12.3.3.100=hbdd6827_1
  - libnpp-dev=12.3.3.100=hbdd6827_1
  - libnsl=2.0.0=h5eee18b_0
  - libnuma=2.0.19=hee96239_0
  - libnvfatbin=12.8.90=hbdd6827_1
  - libnvfatbin-dev=12.8.90=hbdd6827_1
  - libnvjitlink=12.8.93=hbdd6827_1
  - libnvjitlink-dev=12.8.93=hbdd6827_1
  - libnvjpeg=12.3.5.92=hbdd6827_1
  - libnvjpeg-dev=12.3.5.92=h06a4308_1
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libsanitizer=14.3.0=hd4faa28_4
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=14.3.0=he7458c1_104
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=he137b08_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxkbfile=1.1.0=hf54ef8a_2
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - narwhals=2.7.0=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - ninja=1.13.1=h171cf75_0
  - nsight-compute=2025.1.1.2=h2a415c7_1
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=py310h06a4308_1
  - pcre2=10.46=hf426167_0
  - pillow=11.3.0=py310hb7da693_1
  - pip=25.3=pyhc872135_0
  - plotly=6.3.0=py310he3bba80_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - rdma-core=58.0=h7934f7d_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - sysroot_linux-64=2.28=h3108a97_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wayland=1.24.0=hdac8c69_0
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==2.1.0
      - contourpy==1.3.2
      - cssselect2==0.8.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - docker-pycreds==0.4.0
      - drawsvg==2.4.0
      - fairscale==0.4.6
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - imageio==2.19.3
      - iopath==0.1.10
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.6.2
      - mpmath==1.3.0
      - multiscaledeformableattention==1.0
      - networkx==3.3
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.2.2
      - opencv-python==4.11.0.86
      - pathtools==0.1.2
      - plyfile==1.1.3
      - portalocker==3.2.0
      - promise==2.3
      - protobuf==3.20.3
      - psutil==7.1.3
      - pycocotools==2.0.10
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - rasterizer==0.0.0
      - requests==2.32.5
      - scikit-image==0.19.0
      - scipy==1.8.1
      - sentry-sdk==2.45.0
      - setproctitle==1.3.7
      - shapely==1.8.2
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - svgpathtools==1.2.4
      - svgwrite==1.2.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.2.0
      - tifffile==2025.5.10
      - timm==0.5.4
      - tinycss2==1.5.0
      - torch==2.9.1+cu128
      - torchvision==0.24.1+cu128
      - tqdm==4.64.0
      - triton==3.5.1
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - wandb==0.12.19
      - webcolors==25.10.0
      - webencodings==0.5.1
      - yacs==0.1.8
prefix: /home/chanjbc/miniconda3/envs/raster2seq
